export const categories = [
  { id: "1", name: "Technology" },
  { id: "2", name: "Design & Creative" },
  { id: "3", name: "Business & Finance" },
  { id: "4", name: "Marketing & Sales" },
  { id: "5", name: "Media & Communication" },
  { id: "6", name: "Education & Training" },
  { id: "7", name: "Healthcare & Wellness" },
  { id: "8", name: "Engineering & Manufacturing" },
  { id: "9", name: "Science & Research" },
  { id: "10", name: "Construction & Real Estate" },
  { id: "11", name: "Law & Public Service" },
  { id: "12", name: "Hospitality & Tourism" },
  { id: "13", name: "Fashion & Beauty" },
  { id: "14", name: "Arts & Entertainment" },
  { id: "15", name: "Trades & Skilled Services" },
  { id: "16", name: "Agriculture & Environment" },
  { id: "17", name: "Transportation & Logistics" },
  { id: "18", name: "Nonprofit & Community" },
  { id: "19", name: "Religion & Spirituality" },
  { id: "20", name: "Other" },
];